## Ребров. Урок 5. Домашка

In [10]:
import numpy as np
from numpy import linalg

In [7]:
#Задание 1

A = np.array([[1., 2., 0.], [0., 0., 5.], [3., -4., 2.], [1., 6., 5.], [0., 1., 0.]])

U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A)
D[np.diag_indices(min(A.shape))] = s

print(f'U:\n{U}\nD:\n{D}\nV:\n{V}')

U:
[[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
D:
[[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
V:
[[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


In [5]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.00000000e+00  2.00000000e+00  1.31018987e-15]
 [ 1.93009612e-16 -2.66609409e-15  5.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00  2.00000000e+00]
 [ 1.00000000e+00  6.00000000e+00  5.00000000e+00]
 [-5.49534701e-17  1.00000000e+00 -3.02821608e-17]]


In [40]:
#Задание 2. Норма Евклида

d = D[0]
norm_e = d[0]

norm_E = np.linalg.norm(A, ord=2)

print(f'Норма Евклида:\n{norm_e}\n{norm_E}')

Норма Евклида:
8.824868854820444
8.824868854820444


In [41]:
# Задание 2. Норма Фробениуса

f = 0
for i in D:
    i = i**2
    f += i
norm_f = np.sum([m])**(1/2)
norm_f

norm_F = np.linalg.norm(A, ord=None)

print(f'Норма Фробениуса:\n{norm_f}\n{norm_F}')

Норма Фробениуса:
11.045361017187263
11.045361017187261
