## Ребров. Домашка 4.

### Часть 1

In [104]:
import numpy as np
from numpy import linalg as LA
from pprint import pprint
import scipy
import scipy.linalg as lg
 

In [113]:
#Задание 2a

n = 3
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
a_e = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
r_a = LA.matrix_rank(a)
r_ae = LA.matrix_rank(a_e)

print(f'Задание 2a')
print(f'{a}\n{a_e}')
print(f'Ранг(А) = {r_a}, Ранг(Ае) = {r_ae}')
if r_ae == r_a == n:
    print(f'Система совместна, имеет единственное решение')
elif r_ae == r_a != n:
    print(f'Система совместна, имеет несколько решений')
else:
    print(f'Система не совместна, не имеет решений')

Задание 2a
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг(А) = 3, Ранг(Ае) = 3
Система совместна, имеет единственное решение


In [114]:
#Задание 2б

n = 3
a = np.array([[2, -4, 6], [1, -2, -3], [3, -6, 9]])
a_e = np.array([[2, -4, 6, 1], [1, -2, -3, -2], [3, -6, 9, 5]])
r_a = LA.matrix_rank(a)
r_ae = LA.matrix_rank(a_e)

print(f'Задание 2б')
print(f'{a}\n{a_e}')
print(f'Ранг(А) = {r_a}, Ранг(Ае) = {r_ae}')
if r_ae == r_a == n:
    print(f'Система совместна, имеет единственное решение')
elif r_ae == r_a != n:
    print(f'Система совместна, имеет несколько решений')
else:
    print(f'Система не совместна, не имеет решений')

Задание 2б
[[ 2 -4  6]
 [ 1 -2 -3]
 [ 3 -6  9]]
[[ 2 -4  6  1]
 [ 1 -2 -3 -2]
 [ 3 -6  9  5]]
Ранг(А) = 2, Ранг(Ае) = 3
Система не совместна, не имеет решений


In [115]:
#Задание 2в

n = 3
a = np.array([[1, 2, 5], [3, 1, -8]])
a_e = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
r_a = LA.matrix_rank(a)
r_ae = LA.matrix_rank(a_e)

print(f'Задание 2в')
print(f'{a}\n{a_e}')
print(f'Ранг(А) = {r_a}, Ранг(Ае) = {r_ae}')
if r_ae == r_a == n:
    print(f'Система совместна, имеет единственное решение')
elif r_ae == r_a != n:
    print(f'Система совместна, имеет несколько решений')
else:
    print(f'Система не совместна, не имеет решений')

Задание 2в
[[ 1  2  5]
 [ 3  1 -8]]
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг(А) = 2, Ранг(Ае) = 2
Система совместна, имеет несколько решений


In [116]:
#Задание 3

n = 4
a = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
a_e = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
r_a = LA.matrix_rank(a)
r_ae = LA.matrix_rank(a_e)

print(f'Задание 3')
print(f'{a}\n{a_e}')
print(f'Ранг(А) = {r_a}, Ранг(Ае) = {r_ae}')
if r_ae == r_a == n:
    print(f'Система совместна, имеет единственное решение')
elif r_ae == r_a != n:
    print(f'Система совместна, имеет несколько решений')
else:
    print(f'Система не совместна, не имеет решений')

Задание 3
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг(А) = 4, Ранг(Ае) = 4
Система совместна, имеет единственное решение


### Часть 2

In [109]:
#Задание 5
def LU(A):
    
    
    n = A.shape[0]
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    for i in range(n):
            
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

def forward_substitution(L, b):

    n = L.shape[0]

    y = np.zeros_like(b, dtype=np.double);

    y[0] = b[0] / L[0, 0]

    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

def back_substitution(U, y):

    n = U.shape[0]

    x = np.zeros_like(y, dtype=np.double);

    x[-1] = y[-1] / U[-1, -1]

    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x

def lu_solve(A, b):
    
    L, U = LU(A)
    
    y = forward_substitution(L, b)
    
    return back_substitution(U, y)



In [117]:
#Задание 2а
A = np.array([[1., 2., 4.], [2., 9., 12.], [3., 26., 30.]])
L, U = LU(A)
print(f'Задание 2а:\nL:\n{L}')


Задание 2а:
L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]


In [111]:
#Задание 2б
A = np.array([[1., 1., 2., 4.], [2., 5., 8., 9.], [3., 18., 29., 18.], [4., 22., 53., 33.]])
L, U = LU(A)
print(f'Задание 2б\nL:\n{L}')

Задание 2б
L:
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]


In [112]:
#Задание 3
A = np.array([[2., 1., 3.], [11., 7., 5.], [9., 86., 4.]])
b = np.array([1., -6., -5.])

print(f'Задание 3:\n{lu_solve(A, b)}')

Задание 3:
[-1.  0.  1.]
